# Generated by Django 3.1 on 2024-10-26 22:15

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_auto_20241027_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=authy.models.user_directory_path),
        ),
    ]
