# Generated by Django 3.1 on 2024-10-27 20:25

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_auto_20241027_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=authy.models.user_directory_path),
        ),
    ]
