# Generated by Django 3.1 on 2024-10-27 21:05

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_auto_20241028_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authy.models.user_directory_path),
        ),
    ]
