# Generated by Django 3.1 on 2024-10-27 21:10

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_auto_20241028_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, upload_to=authy.models.user_directory_path),
        ),
    ]
